### ISSUE TITLE
When running the evaluate.py file, RuntimeError raised: missing key(s) and size mismatch for the other keys

### ISSUE THREAD

**Issue by HIT-CS-Kn1ght** [seermer/HollowKnight_RL#3]
When loading the the bestmodel.pt, which was provided in the url:https://drive.google.com/drive/folders/1EOlSS6pknAID04wfB2AmB2XZCnuEHWxH?usp=sharing
by the author, or loading the latestoptimizer.pt which was trained by myself, the evaluate.py raised RuntimeError:
1. Missing key(s) in state_dict: "resetable.0.mu_W", "resetable.0.sigma_W", "resetable.0.mu_bias", ...
2. size mismatch for noisy.0.mu_W: copying a param with shape torch.Size([320, 11520]) from checkpoint, the shape in current model is torch.Size([512, 8000])...
I wonder how to set the right model and weight. Thanks a lot!

**Comment by seermer** [comment]
Hi, I am sorry for the very late response, I was quite busy. I think this is because the model was trained on an older version of the code, so the model does not match with the newer code. If you are still interested, you can try the hornet branch instead of the main branch, which did not have resettable implemented.

**Comment by HIT-CS-Kn1ght** [comment]
Get it. Thanks a lot!
